// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BeeListerExpansion allows custom methods to be added to
// BeeLister.
type BeeListerExpansion interface{}

// BeeNamespaceListerExpansion allows custom methods to be added to
// BeeNamespaceLister.
type BeeNamespaceListerExpansion interface{}
