// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	insect "k8s-p/pkg/apis/insect"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Bee)(nil), (*insect.Bee)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Bee_To_insect_Bee(a.(*Bee), b.(*insect.Bee), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*insect.Bee)(nil), (*Bee)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_insect_Bee_To_v1beta1_Bee(a.(*insect.Bee), b.(*Bee), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeeList)(nil), (*insect.BeeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BeeList_To_insect_BeeList(a.(*BeeList), b.(*insect.BeeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*insect.BeeList)(nil), (*BeeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_insect_BeeList_To_v1beta1_BeeList(a.(*insect.BeeList), b.(*BeeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeeSpec)(nil), (*insect.BeeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BeeSpec_To_insect_BeeSpec(a.(*BeeSpec), b.(*insect.BeeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*insect.BeeSpec)(nil), (*BeeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_insect_BeeSpec_To_v1beta1_BeeSpec(a.(*insect.BeeSpec), b.(*BeeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeeStatus)(nil), (*insect.BeeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BeeStatus_To_insect_BeeStatus(a.(*BeeStatus), b.(*insect.BeeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*insect.BeeStatus)(nil), (*BeeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_insect_BeeStatus_To_v1beta1_BeeStatus(a.(*insect.BeeStatus), b.(*BeeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeeStatusStrategy)(nil), (*insect.BeeStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BeeStatusStrategy_To_insect_BeeStatusStrategy(a.(*BeeStatusStrategy), b.(*insect.BeeStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*insect.BeeStatusStrategy)(nil), (*BeeStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_insect_BeeStatusStrategy_To_v1beta1_BeeStatusStrategy(a.(*insect.BeeStatusStrategy), b.(*BeeStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeeStrategy)(nil), (*insect.BeeStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BeeStrategy_To_insect_BeeStrategy(a.(*BeeStrategy), b.(*insect.BeeStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*insect.BeeStrategy)(nil), (*BeeStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_insect_BeeStrategy_To_v1beta1_BeeStrategy(a.(*insect.BeeStrategy), b.(*BeeStrategy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Bee_To_insect_Bee(in *Bee, out *insect.Bee, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_BeeSpec_To_insect_BeeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_BeeStatus_To_insect_BeeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Bee_To_insect_Bee is an autogenerated conversion function.
func Convert_v1beta1_Bee_To_insect_Bee(in *Bee, out *insect.Bee, s conversion.Scope) error {
	return autoConvert_v1beta1_Bee_To_insect_Bee(in, out, s)
}

func autoConvert_insect_Bee_To_v1beta1_Bee(in *insect.Bee, out *Bee, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_insect_BeeSpec_To_v1beta1_BeeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_insect_BeeStatus_To_v1beta1_BeeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_insect_Bee_To_v1beta1_Bee is an autogenerated conversion function.
func Convert_insect_Bee_To_v1beta1_Bee(in *insect.Bee, out *Bee, s conversion.Scope) error {
	return autoConvert_insect_Bee_To_v1beta1_Bee(in, out, s)
}

func autoConvert_v1beta1_BeeList_To_insect_BeeList(in *BeeList, out *insect.BeeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]insect.Bee)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_BeeList_To_insect_BeeList is an autogenerated conversion function.
func Convert_v1beta1_BeeList_To_insect_BeeList(in *BeeList, out *insect.BeeList, s conversion.Scope) error {
	return autoConvert_v1beta1_BeeList_To_insect_BeeList(in, out, s)
}

func autoConvert_insect_BeeList_To_v1beta1_BeeList(in *insect.BeeList, out *BeeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Bee)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_insect_BeeList_To_v1beta1_BeeList is an autogenerated conversion function.
func Convert_insect_BeeList_To_v1beta1_BeeList(in *insect.BeeList, out *BeeList, s conversion.Scope) error {
	return autoConvert_insect_BeeList_To_v1beta1_BeeList(in, out, s)
}

func autoConvert_v1beta1_BeeSpec_To_insect_BeeSpec(in *BeeSpec, out *insect.BeeSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_BeeSpec_To_insect_BeeSpec is an autogenerated conversion function.
func Convert_v1beta1_BeeSpec_To_insect_BeeSpec(in *BeeSpec, out *insect.BeeSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_BeeSpec_To_insect_BeeSpec(in, out, s)
}

func autoConvert_insect_BeeSpec_To_v1beta1_BeeSpec(in *insect.BeeSpec, out *BeeSpec, s conversion.Scope) error {
	return nil
}

// Convert_insect_BeeSpec_To_v1beta1_BeeSpec is an autogenerated conversion function.
func Convert_insect_BeeSpec_To_v1beta1_BeeSpec(in *insect.BeeSpec, out *BeeSpec, s conversion.Scope) error {
	return autoConvert_insect_BeeSpec_To_v1beta1_BeeSpec(in, out, s)
}

func autoConvert_v1beta1_BeeStatus_To_insect_BeeStatus(in *BeeStatus, out *insect.BeeStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_BeeStatus_To_insect_BeeStatus is an autogenerated conversion function.
func Convert_v1beta1_BeeStatus_To_insect_BeeStatus(in *BeeStatus, out *insect.BeeStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_BeeStatus_To_insect_BeeStatus(in, out, s)
}

func autoConvert_insect_BeeStatus_To_v1beta1_BeeStatus(in *insect.BeeStatus, out *BeeStatus, s conversion.Scope) error {
	return nil
}

// Convert_insect_BeeStatus_To_v1beta1_BeeStatus is an autogenerated conversion function.
func Convert_insect_BeeStatus_To_v1beta1_BeeStatus(in *insect.BeeStatus, out *BeeStatus, s conversion.Scope) error {
	return autoConvert_insect_BeeStatus_To_v1beta1_BeeStatus(in, out, s)
}

func autoConvert_v1beta1_BeeStatusStrategy_To_insect_BeeStatusStrategy(in *BeeStatusStrategy, out *insect.BeeStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1beta1_BeeStatusStrategy_To_insect_BeeStatusStrategy is an autogenerated conversion function.
func Convert_v1beta1_BeeStatusStrategy_To_insect_BeeStatusStrategy(in *BeeStatusStrategy, out *insect.BeeStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_BeeStatusStrategy_To_insect_BeeStatusStrategy(in, out, s)
}

func autoConvert_insect_BeeStatusStrategy_To_v1beta1_BeeStatusStrategy(in *insect.BeeStatusStrategy, out *BeeStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_insect_BeeStatusStrategy_To_v1beta1_BeeStatusStrategy is an autogenerated conversion function.
func Convert_insect_BeeStatusStrategy_To_v1beta1_BeeStatusStrategy(in *insect.BeeStatusStrategy, out *BeeStatusStrategy, s conversion.Scope) error {
	return autoConvert_insect_BeeStatusStrategy_To_v1beta1_BeeStatusStrategy(in, out, s)
}

func autoConvert_v1beta1_BeeStrategy_To_insect_BeeStrategy(in *BeeStrategy, out *insect.BeeStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1beta1_BeeStrategy_To_insect_BeeStrategy is an autogenerated conversion function.
func Convert_v1beta1_BeeStrategy_To_insect_BeeStrategy(in *BeeStrategy, out *insect.BeeStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_BeeStrategy_To_insect_BeeStrategy(in, out, s)
}

func autoConvert_insect_BeeStrategy_To_v1beta1_BeeStrategy(in *insect.BeeStrategy, out *BeeStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_insect_BeeStrategy_To_v1beta1_BeeStrategy is an autogenerated conversion function.
func Convert_insect_BeeStrategy_To_v1beta1_BeeStrategy(in *insect.BeeStrategy, out *BeeStrategy, s conversion.Scope) error {
	return autoConvert_insect_BeeStrategy_To_v1beta1_BeeStrategy(in, out, s)
}
